/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.ConnectionProvider;
/**
 *
 * @author 91844
 */
public class newstudent extends javax.swing.JFrame {

    /**
     * Creates new form newstudent
     */
    public newstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        coursebox = new javax.swing.JComboBox();
        branchbox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Father Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Course Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        sname.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 270, -1));

        name.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 268, -1));

        fname.setBackground(new java.awt.Color(255, 255, 204));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 270, -1));

        coursebox.setBackground(new java.awt.Color(255, 255, 204));
        coursebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B.Tech" }));
        coursebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseboxActionPerformed(evt);
            }
        });
        getContentPane().add(coursebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 270, -1));

        branchbox.setBackground(new java.awt.Color(255, 255, 204));
        branchbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "IT", "MECHATRONICS", "EC" }));
        branchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchboxActionPerformed(evt);
            }
        });
        getContentPane().add(branchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 270, -1));

        t1.setBackground(new java.awt.Color(255, 255, 204));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Name", "Father Name", "Course Name", "Branch Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 594, 110));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/save-icon--1.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/red-x-mark-transparent-background-3.png"))); // NOI18N
        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/123456.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Branch Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/123456.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseboxActionPerformed

    private void branchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchboxActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_branchboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        
                     try
                      {   
                          Class.forName("org.apache.derby.jdbc.ClientDriver");
                          Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/tiya ");
                          String StudentId=sname.getText();
        String Name=name.getText();
        String FatherName=fname.getText();
        String CourseName=(String)coursebox.getSelectedItem();
        String branchName=(String)branchbox.getSelectedItem();
                          Statement st=con.createStatement();
                          String query = "insert into newstudent values('"+StudentId+"','"+Name+"','"+FatherName+ "','"+CourseName+"','"+branchName+"')";
                          st.executeUpdate(query);
                          JOptionPane.showMessageDialog(null,"Successfully updated");
                          
                          
                          
                           Statement s=con.createStatement();
                           String q="Select * from newstudent";
                           ResultSet rs=s.executeQuery(q);
                           while(rs.next())
                           {
                               String   sid = rs.getString("STUDENT_ID");
                               String   name = rs.getString("NAME");
                                  String   FNAME = rs.getString("FATHER_NAME");
                                  String   COURSENAME = rs.getString("COURSE_NAME");
                                  String   BRANCHNAME = rs.getString("BRANCH_NAME");
                                  
                               
                                  String tbData[]={  sid,name,FNAME, COURSENAME, BRANCHNAME };
                                   DefaultTableModel dtm=(DefaultTableModel) t1.getModel();
                                   
                              
                               dtm.addRow(tbData);
                           }
                          
                          
                      }
                      catch(Exception e)
                      {
                          JOptionPane.showMessageDialog(null,"Student data added succesfully");
                          System.out.println(e.getMessage());
                          
                          setVisible(false);
                          new newstudent().setVisible(true);
                      }
                      
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {
              Connection c=ConnectionProvider.getCon();
      
                      String StudentId=sname.getText();
               Statement st=c.createStatement();
               if(StudentId.isEmpty())
               {
                          JOptionPane.showMessageDialog(null,"One or more fields are empty");
               }
            else
               {
                   String query = "delete from newstudent where STUDENT_ID='"+StudentId +"'";
                          st.executeUpdate(query);
                             JOptionPane.showMessageDialog(null,"Student detatil removed successfully");
                             sname.setText("");
                   
               }
// TODO add your handling code here:
        } 
        catch (SQLException e) {
          System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox branchbox;
    private javax.swing.JComboBox coursebox;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sname;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
